name: Setup Java
on:
  workflow_dispatch:
    inputs:
      java_version:
        default: "17"
        description: select the java version
        type: choice
        options:
          - "11"
          - "17"
          - "21"
permissions:
  contents: read
  id-token: write
jobs:
  build:
    uses: tcslabsfjbs/gh-actions/.github/workflows/hello.yaml@main
    with:
      java_ver: ${{ inputs.java_version }}
